[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "librosa>=0.11.0",
    "numpy>=2.2.6",
    "scikit-learn>=1.7.2",
    "scipy>=1.16.2",
    "sounddevice>=0.5.2",
    "streamlit>=1.49.1",
]
